seiketsu/Dash/urls.py
from . import views
from django.urls import path, include

from django.contrib.auth import views as auth_views

app_name = 'Dash'

urlpatterns = [
    # path('loged_in', views.index),
    #path('', views.login),
    path('partner-werden/', views.partner_werden, name='partner_werden'),
    path('vision/', views.vision, name='vision'),
    path('blog/', views.blog_overview, name='blog_overview'), 
    path('blog_post01/', views.blog_post01, name='blog_post01'),
    path('blog_post02/', views.blog_post02, name='blog_post02'),
    path('blog_post03/', views.blog_post03, name='blog_post03'),
    path('blog_post04/', views.blog_post04, name='blog_post04'),
    path('blog_post05/', views.blog_post05, name='blog_post05'),   
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('remove_materials/', views.remove_materials, name="remove_materials"),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('modify_user_profile/', views.modify_user_profile,
         name='modify_user_profile'),
    path('add_gln/', views.add_gln, name='add_gln'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='dash/dashboard/profile/change_password.html',
        success_url='/dash/user_profile'), name='change_password'),
    path("select2/", include("django_select2.urls")),
    path('nearby/', views.nearby, name="nearby"),
    path('admin/import_material_AT',
         views.import_material_AT, name='import_material_AT'),
    path('admin/import_material_EU',
         views.import_material_EU, name='import_material_EU'),
    #re_path(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', name='jsi18n'),
    path('contact-landfill/', views.contact_landfill, name='contact-landfill'),
]

seiketsu/seiketsu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Dash import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('dash/', include('Dash.urls'), name='dash'),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

seiketsu/Dash/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from .forms import AddGLN, AddOpeningHours, ChangeAdressData, UserForm_Deponie, UserProfileInfo_Deponie, \
    UserForm_Bauunternehmer, UserProfileInfo_Bauunternehmer, UserProfileInfo_Deponie, SearchLandfills, \
    LandfillsSearchResult
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
import django.contrib.messages as messages
from django import forms
from django.forms import formset_factory, modelformset_factory
from django.conf import settings
from django.views import generic
from django.contrib.gis.geos import fromstr
from django.contrib.gis.db.models.functions import Distance
from .models import Country, Deponie, Bauunternehmer, Materialien_AT, Materialien_EU, Opening_Hours, User_Adress, gis_Location, gln_Data
from django.contrib.auth.models import User, Group
from django.contrib.gis.geos.point import Point
import requests
import urllib.parse
from Dash.functions.parser_abfallkodex_austria import material_importer
from django.core.mail import BadHeaderError
from django.core import mail
from django.core.mail import EmailMultiAlternatives, send_mail

from pprint import pprint

DASH_NEARBY_HTML = 'dash/nearby.html'
CONTACT_LANDFILL_HTML = 'dash/contact-landfill.html'


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.EmailField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': '', 'id': 'hello'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': '',
            'id': 'hi',
        }
    ))


@login_required
def special(request):
    return HttpResponse("you are logged in")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))


def index(request):
    return render(request, 'dash/index.html')

def partner_werden(request):
    return render(request, 'dash/partner-werden.html')

def vision(request):
    return render(request, 'dash/vision.html')

def blog_overview(request):
    return render(request, 'dash/blog/blog_overview.html')

#---single blog posts, need to be done dynamically later ---#

def blog_post01(request):
    return render(request, 'dash/blog/blog_post1.html')
def blog_post02(request):
    return render(request, 'dash/blog/blog_post2.html')
def blog_post03(request):
    return render(request, 'dash/blog/blog_post3.html')
def blog_post04(request):
    return render(request, 'dash/blog/blog_post4.html')
def blog_post05(request):
    return render(request, 'dash/blog/blog_post5.html')

def register(request):
    registered = False
    user_form_deponie = UserForm_Deponie()
    profile_form_deponie = UserProfileInfo_Deponie()
    user_form_bauunternehmer = UserForm_Bauunternehmer()
    profile_form_bauunternehmer = UserProfileInfo_Bauunternehmer()

    if request.method == "POST":
        account_type = request.POST.get('account_type')
        if account_type == 'abfallbehandler':
            user_form_deponie = UserForm_Deponie(data=request.POST)
            profile_form_deponie = UserProfileInfo_Deponie(data=request.POST)

            if user_form_deponie.is_valid() and profile_form_deponie.is_valid():
                user = user_form_deponie.save()
                user.set_password(user.password)
                add_to_group = Group.objects.get(name='Abfallbehandler')
                add_to_group.user_set.add(user)
                user.save()
                profile = profile_form_deponie.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form_deponie.errors, profile_form_deponie.errors)

        elif account_type == 'bauunternehmer':
            user_form_bauunternehmer = UserForm_Bauunternehmer(
                data=request.POST)
            profile_form_bauunternehmer = UserProfileInfo_Bauunternehmer(
                data=request.POST)

            if user_form_bauunternehmer.is_valid() and profile_form_bauunternehmer.is_valid():
                user = user_form_bauunternehmer.save()
                user.set_password(user.password)
                add_to_group = Group.objects.get(name='Bauunternehmer')
                add_to_group.user_set.add(user)
                user.save()
                profile = profile_form_bauunternehmer.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form_bauunternehmer.errors,
                      profile_form_bauunternehmer.errors)

    return render(request, 'dash/registration.html', {'user_form_deponie': user_form_deponie,
                                                      'profile_form_deponie': profile_form_deponie,
                                                      'user_form_bauunternehmer': user_form_bauunternehmer,
                                                      'profile_form_bauunternehmer': profile_form_bauunternehmer,
                                                      'registered': registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/dash/dashboard')

            else:
                return HttpResponse("UPPPSSS Something went wrong")
        else:
            print("someone tried to do the old hackedy hack")
            print("Username: {}".format(username))
            return HttpResponse("Computer says no!")

    else:
        return render(request, 'dash/login.html', {})


@login_required
def dashboard(request):
    return render(request, 'dash/dashboard/dashboard.html', {})


@login_required
def user_profile(request):
    if request.method == "GET":
        user_model_data = User.objects.get(pk=request.user.id)
        user_models = [Bauunternehmer, Deponie]
        primary_adress = None
        for model in user_models:
            try:
                current_user = model.objects.get(user=request.user.id)

                if current_user:
                    break
            except:
                messages.error(request, "User Data could not be found")
        try:
            user_adress_data = User_Adress.objects.all().filter(user=request.user.id)
            for adress_item in user_adress_data:
                if adress_item.is_primary_adress is True:
                    primary_adress = adress_item
                    break
        except:
            primary_adress = None

        try:
            user_gln_data = gln_Data.objects.all().filter(user=request.user.id)
            gln_data_container = []
            for data_item in user_gln_data:
                gln_data_container.append(data_item)
        except:
            gln_data_container = None

    if request.method == "POST":

        if request.POST['delete_gln']:
            gln_to_delete = gln_Data.objects.get(id=request.POST['delete_gln'])
            opening_days_to_delete = Opening_Hours.objects.all().filter(
                location=gln_to_delete.location)
            adress_to_delete = User_Adress.objects.get(
                id=gln_to_delete.adress.id)
            gis_location_to_delete = gis_Location.objects.get(
                id=gln_to_delete.location.id)
            gln_to_delete.delete()
            opening_days_to_delete.delete()
            adress_to_delete.delete()
            gis_location_to_delete.delete()

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, 'dash/dashboard/profile/user_profile.html',
                  {'usermodel_data': user_model_data, 'usermodel_type_data': current_user,
                   'usermodel_adress_data': primary_adress, 'usermodel_gln_data': gln_data_container, })


@login_required
def modify_user_profile(request):
    if request.method == "GET":
        try:
            user_adress_data = User_Adress.objects.all().filter(user=request.user.id)
            user_model_data = User.objects.get(pk=request.user.id)
            for adress_item in user_adress_data:
                if adress_item.is_primary_adress is True:
                    primary_adress = adress_item
                    break
            update_adress_form = ChangeAdressData(instance=primary_adress)
        except:
            update_adress_form = ChangeAdressData()

    if request.method == "POST":
        # user_adress = User_Adress.objects.get(user=)
        user_adress_form = ChangeAdressData(data=request.POST)
        user_model_data = User.objects.get(pk=request.user.id)
        if user_adress_form.is_valid():
            current_adress_form = user_adress_form.save(commit=False)
            current_adress_form.is_primary_adress = True
            current_adress_form.user = request.user
            current_adress_form.save()
            user_model_data.first_name=request.POST['company_name']
            user_model_data.save()
           
        return HttpResponseRedirect('/dash/user_profile')
    
    

    return render(request, 'dash/dashboard/profile/modify_user_profile.html', {'adress_form': update_adress_form, 'user_model_data':user_model_data})


@login_required
def remove_materials(request):
    material_ids_to_remove = request.POST.getlist('materials_to_remove[]')

seiketsu/templates/dash/blog/blog_overview.html
{% extends "dash/base.html" %}{%load static%}{% block body_block %}
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


    <div class="container blog">
        
        <div class="py-4">

            <h1 style="text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">Willkommen im Blog</h1>

        </div>
        <!---------------------- context ------------------->
        <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
            integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous"
            async></script>
        <div class="row" data-masonry='{"percentPosition": true }'
            style="position: relative; height: 81vw; width: 100%;">
            <div class="col-sm-6 col-lg-4 mb-4" style="position: absolute; left: 0%; top: 0px;">
                <div class="card text-justify fett p-0">

                    <svg class="card-img-top revi-favi w-100" xmlns="http://www.w3.org/2000/svg"
                        enable-background="new 0 0 20 20" height="48px" viewBox="0 0 20 20" width="48px" fill="#228c22">
                        <rect fill="none" height="20" width="20" />
                        <path
                            d="M13,14h3.83l-1.09,2.17C15.49,16.68,14.97,17,14.4,17H13 M7.62,7.72l1.8-3L8.52,3.23c-0.39-0.65-1.33-0.65-1.72,0L5.05,6.17 L7.62,7.72z M16.34,8.49L13.72,10l1.83,3h0.85c0.57,0,1.09-0.32,1.34-0.83c0.23-0.46,0.21-1-0.06-1.44L16.34,8.49z M4.37,15.08 c-0.22,0.37-0.24,0.83-0.05,1.22C4.54,16.73,4.98,17,5.46,17H8.5v-3H5.02L4.37,15.08z M13,14v-1.54l-3,3l3,3V17 M14.01,4.6 l-1.13-1.88C12.62,2.28,12.13,2,11.6,2H8.95l2.49,4.15l-1.29,0.77l4.12,1.03l1.03-4.12L14.01,4.6z M5.3,11.58l1.28,0.77L5.56,8.23 L1.44,9.26l1.29,0.77l-0.42,0.69c-0.26,0.44-0.28,0.98-0.06,1.44l1.22,2.44L5.3,11.58z" />
                    </svg>
                    <div class="card-body justify-content-start contact-body">
                        <h5 class="card-title">Kreislaufwirtschaft in der Baubranche: so können wir den Wandel
                            mitgestalten
                        </h5>
                        <p class="card-text pb-2">Da natürliche Ressourcen endlich sind und sich das Klima verändert,
                            müssen
                            wir uns vom derzeitigen Gesellschaftsmodell Ausbeuten - Produzieren - Wegwerfen lösen und zu
                            einer kreislauffähigen Wirtschaft übergehen. </p>
                        <p></p>
                        <a href="{%url 'Dash:blog_post01'%}" target="_blank" class="knopf mb-2">Hier weiter lesen</a>
                       
                    </div>
                </div>
            </div>
            <!-- The Modal -->
            <div class="col-sm-6 col-lg-4 mb-4" style="position: absolute; top:0px; left: 66.6%;">
                <div class="card col text-justify fett p-0 ">
                    <img class="card-img-top" src="{% static '/images/blog/thumbnail_2_small.jpg' %}">
                    <p class="text-muted text-end py-1 px-2" style="font-size: small">Foto von El Bravo von Pexels</p>
                    <div class="card-body pb-4">
                        <h5 class="card-title">Von wegen Kreislaufwirtschaft: das dreckige Geschäft mit dem Handel von
                            CO2-Zertifikaten </h5>
                        <p class="card-text pb-2">Beton, er wird überall gebraucht. Für den Bau von Straßen und Brücken,
                            Wohnungen und Fabriken. Doch gleichzeitig ist er einer der größten Klimakiller. Allein bei
                            seiner Herstellung entstehen jedes Jahr mehr als 50 Millionen Tonnen CO-2. Diese Emissionen
                            müssen schnell gesenkt werden, wenn wir unsere Klimaziele erreichen wollen.
                        </p>
                        <a href="{%url 'Dash:blog_post02'%}" target="_blank" class="knopf">Mehr gibts
                            hier!</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4 mb-4" style="position: absolute; top: 600px;">
                <div class="card col text-justify fett px-0 pt-3">
                    <div class="card-body pb-4">
                        <h5 class="card-title">Wie funktioniert der Handel mit CO-2-Zertifikate?</h5>
                        <p class="card-text pb-2">Weltweit existieren unzählige Emissionshandelssysteme und damit je
                            nach Region auch unterschiedliche CO2-Preise. Das mit Abstand größte Handelssystem ist das
                            der Europäischen Union, welches 2003 in Brüssel beschlossen wurde und seit 2005 in Kraft
                            ist.
                        </p>
                        <a href="{%url 'Dash:blog_post03'%}" target="_blank" class="knopf">Lesen Sie weiter</a>
                    </div>
                </div>

            </div>
            <div class="col-sm-6 col-lg-4 mb-4" style="position: absolute; left: 33.3333%; ">
                <div class="card col text-justify fett px-0 pt-3">
                    <div class="card-body pb-4">
                        <h5 class="card-title">Baustoffrecycling: der harte Weg zur Akzeptanz</h5>
                        <p class="card-text pb-2">Mineralische Abfälle stellen mengenmäßig einen der größten
                            Abfallströme in Europa dar. Allein in Deutschland fallen jedes Jahr über 200 Mio. Tonnen an.
                            Häufig werden Aushubmaterialien kilometerweit quer durchs Land transportiert. Das verursacht
                            nicht nur enorme Kosten für die Unternehmen, sondern auch einen zunehmenden logistischen
                            Aufwand.
                        </p>
                        <a href="{%url 'Dash:blog_post04'%}" target="_blank" class="knopf">Lesen Sie weiter</a>
                    </div>
                </div>

            </div>
            <div class="col-sm-6 col-lg-4 mb-4" style="position: absolute; left: 33.3333%;top: 525px;">
                <div class=" card col text-justify fett p-0 ">
                    <img class=" card-img-top" src="{% static '/images/blog/thumbnail3.jpg' %}">

                    <div class="card-body pb-4">
                        <h5 class="card-title">Digitale Transformation von Recyclingdeponien: So kann es gelingen</h5>
                        <p class="card-text pb-2">Würde man Deutschland mit einem Unternehmen beschreiben, dann
                            vielleicht
                            Nokia, Kodak oder Quelle. Unternehmen, die einmal erfolgreich waren und lange Zeit den Markt
                            dominierten. Heute sind sie nur noch halb so groß oder aufgelöst. Beide wurden Opfer eines
                            Managementfehlers – dem Innovationsdilemma.
                        </p>
                        <a href="{%url 'Dash:blog_post05'%}" target="_blank" class="knopf">Mehr gibts
                            hier!</a>
                    </div>
                </div>
            </div>

        </div>
 
        </div>

    </div>
    {% endblock %}

seiketsu/templates/dash/blog/blog_post1.html
{% extends "dash/base.html" %}{%load static%}{% block body_block %}
   
        <!---------------------- context ------------------->
        <div id="fh5co-services-section" >
            <div class="container py-5" style="">
                <div class="row pt-5">

                <div class="col pb-4">
                    <h3 class="text-bold py-4">Kreislaufwirtschaft in der Baubranche: <br>so
                        können
                        wir den Wandel
                        mitgestalten
                    </h3>
                    <div class="pb-2 row">
                        <div class="col-sm-7">
                            <p>Da natürliche Ressourcen endlich sind und sich
                                das Klima verändert, müssen wir uns vom derzeitigen Gesellschaftsmodell
                                <b>Ausbeuten - Produzieren - Wegwerfen</b> lösen und zu einer kreislauffähigen
                                Wirtschaft
                                übergehen. Gerade jetzt wird die Unsicherheit der Ressourcen und die Anfälligkeit von
                                Lieferketten sichtbar. Im März 2020 legte die Europäische Kommission einen Aktionsplan
                                für
                                die
                                Kreislaufwirtschaft vor, der sich vor allem auf Abfallvermeidung und -management
                                konzentriert
                                und darauf abzielt, das Wirtschaftswachstum und die Wettbewerbsfähigkeit zu steigern.
                            </p>
                            <p> Im Aktionsplan wird die nachhaltige Transformation des Bausektors hervorgehoben. Der
                                Sektor
                                ist
                                ein wesentlicher Bestandteil, um unsere Klimaziele zu erreichen. Er beansprucht große
                                Mengen
                                an
                                Ressourcen, etwa 50 % aller gewonnenen Rohstoffe. Gleichzeitig ist die Branche für über
                                35 %
                                des
                                gesamten Abfallaufkommens in der Europäischen Union verantwortlich. Die
                                Treibhausgasemissionen
                                aus der Materialgewinnung, der Herstellung von Bauprodukten sowie dem Bau und der
                                Renovierung
                                von Gebäuden werden auf 5 bis 12% der gesamten nationalen Treibhausgasemissionen
                                geschätzt.
                                Durch eine höhere Materialeffizienz könnten bis zu 80 % dieser Emissionen eingespart
                                werden.
                            </p>

                            <p> Um die Materialeffizienz zu steigern und die Klimaauswirkungen zu verringern, entwickeln
                                wir
                                mit
                                Revitalyze eine umfassend neue Plattform, die auf bisherige Erfahrungen aus der Branche
                                beruht.
                                Die Plattform sorgt für Kohärenz in allen relevanten Bereichen wie Ressourceneffizienz,
                                Management von Bau- und Abbruchabfällen, Zugänglichkeit und Digitalisierung. Wir werden
                                Initiativen im Einklang mit den Grundsätzen der Kreislaufwirtschaft umsetzen,
                                insbesondere
                                im
                                Hinblick auf eine optimierte Materiallogistik, Beschaffung- und Verwertung. Für Nutzer
                                unserer
                                Plattform wird die neue Überarbeitung der in den EU-Rechtsvorschriften für Bau- und
                                Abbruchabfälle festgelegten Ziele für die Materialverwertung durch eine sichere,
                                nachhaltige
                                und
                                zirkuläre Nutzung mehrere Vorteile haben.
                            <p class="text-end text-muted" style="position: relative; right: 10em; font-size: small"> ~David Plaseller~ <br> CEO
                                Revitalyze</p>
                            </p>
<div class="row d-flex justify-content-start">
                        <div class="col d-flex justify-content-start pb-3 px-5">
                            <a href="{%url 'Dash:blog_overview'%}"" target="" class="knopf">zurück zur Artikelübersicht</a>
                        </div>
                    </div>
                        </div>
                        <div class="col-sm-5 text-center"><img class="" style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px;
                        height: 65%" src="{% static '/images/blog/blog_post1.jpg' %}">
                            <p class="text-muted pt-2 text-center" style="position:relative; left: 4em; font-size: small">Foto von Francesco Ungaro von Pexels
                            </p>
                        </div>

                    </div>
                    

                </div>
            </div>

        </div>
    </div>

        {% endblock %}

seiketsu/templates/dash/blog/blog_post3.html
{% extends "dash/base.html" %}{%load static%}{% block body_block %}
   
        <!---------------------- context ------------------->
        <div id="fh5co-services-section" >
            <div class="container py-5" style="">
                <div class="row">
            <div class="col blog-article-body fett p-0 ">

                <div class="row pb-4">
                    <h3 class=" text-bold py-4">Wie funktioniert der Handel mit CO-2-Zertifikate?

                    </h3>
                    <div class="pb-2 row">

                        <div class="col">

                            <figure class="float-start"><img style="max-height: 500px; box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; margin: 5px 15px 0 0; padding: 0"
                                    class="float" src="{% static '/images/blog/blog_post3.jpg' %}">
                                <figcaption class="text-muted" style="font-size: small">Foto von Chris
                                    LeBoutillier
                                    von
                                    Pexels</figcaption>
                            </figure>

                            <p>Weltweit existieren unzählige Emissionshandelssysteme und damit je nach Region auch
                                unterschiedliche CO2-Preise. Das mit Abstand größte Handelssystem ist das der
                                Europäischen Union, welches 2003 in Brüssel beschlossen wurde und seit 2005 in Kraft
                                ist. Neben den 27 Mitgliedstaaten der EU nehmen auch Liechtenstein, die Schweiz, Island
                                und Norwegen am Emissionshandel teil.</p>

                            <p>
                                Neben dem europäischen Modell haben beispielsweise auch die USA und Kanada sowie
                                einzelne Bundesstaaten ihre individuellen Handelssysteme. Im Januar 2021 hat auch die
                                deutsche Regierung ihr eigenes System für den Handel mit Emissionszertifikaten
                                eingeführt und hat als Teil des Klimaschutzprogramms einen nationalen CO2-Preis
                                festgelegt, der den europäischen Zertifikatehandel ergänzen soll. Seit Anfang des Jahres
                                müssen deutsche Unternehmen, die fossile Brennstoffe wie Erdgas und Heizöl in den
                                Verkehr bringen, für jede Tonne ausgestoßenes CO2 ein Zertifikat kaufen. Betroffen sind
                                beispielsweise Raffinerien oder Öl-Importeure, aber auch die Autoindustrie. Letztlich
                                verfolgen alle nationalen wie internationalen Handelssysteme ähnliche Ziele: Es soll
                                sich finanziell lohnen, weniger Treibhausgase auszustoßen und stattdessen auf
                                umweltfreundlichere Prozesse und Lösungen zu setzen. Auf Solar- und Windenergie
                                beispielsweise. Das funktioniert aber nur, wenn der Ausstoß immer teurer wird. Das
                                Problem dabei ist, Verbraucher:innen müssen zwar keine Zertifikate kaufen, jedoch geben
                                viele Unternehmen die zusätzlichen Kosten für den Erwerb der Zertifikate auf an
                                Kund:innen weiter.</p>
                            <p>
                            <h5>Wodurch steigt der CO2-Preis?</h5>
                            Viele Zertifikate-Systeme sind marktbasiert und funktionieren nach dem sogenannten “Cap
                            and Trade” System. Zu deutsch: Begrenzung und Handel. Zunächst werden CO2-Zertifikate
                            kostenlos in begrenzter Anzahl von staatlicher Stelle ausgegeben oder zu einem
                            festgelegten Preis verkauft, wie es aktuell bei den deutschen Emissionsrechten der Fall
                            ist. Nach einer Einführungsphase soll dann der Markt bestimmen, wie viel Wirtschaft und
                            Industrie für die Tonne CO2 hinblättern müssen. Denn die Papiere werden anschließend an
                            Klima- und Strombörsen wie der European Climate Exchange (ECX) in London oder der
                            European Energy Exchange (EEX) in Leipzig versteigert und gehandelt. Unternehmen können
                            überschüssige Zertifikate dort verkaufen, falls sie weniger benötigen – und wer
                            Nachschub braucht, muss ebenfalls über die Börse gehen.
                            </p>
                            <p>
                                Der Preis für CO2 ist also ähnlich eines Aktienkurses dem Spiel aus Angebot und
                                Nachfrage ausgeliefert. Mit dem Unterschied, dass die Politik in das System eingreift:
                                Sie verknappt das Angebot an Zertifikaten (Cap), indem sie die erlaubte Obergrenze für
                                Treibhausgasemissionen Jahr für Jahr herabsetzt. Bis 2030 soll zum Beispiel die
                                Maximalgrenze für europäische Emissionsrechte um 2,2% pro Jahr sinken. Konkret bedeutet
                                das: Jedes Jahr werden rund 48 Mio. Zertifikate weniger ausgegeben als ein Jahr zuvor.
                                Das Angebot soll sukzessive sinken und der Preis dadurch stetig steigen.


                            <p class="text-muted" style="font-size: small"> ~David Plaseller~ <br> CEO
                                Revitalyze</p>
                            </p>
                            </p>
                        </div>
                        <div class="row d-flex justify-content-end">
                            <div class="col d-flex justify-content-end pb-3 px-5">
                                <a href="{%url 'Dash:blog_overview'%}"" target="" class="knopf">zurück zur Artikelübersicht</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>


        {% endblock %}