seiketsu/Dash/urls.py
from . import views
from django.urls import path, include

from django.contrib.auth import views as auth_views

app_name = 'Dash'

urlpatterns = [
    # path('loged_in', views.index),
    #path('', views.login),
    path('partner-werden/', views.partner_werden, name='partner_werden'),
    path('vision/', views.vision, name='vision'),
    path('blog/', views.blog_overview, name='blog_overview'), 
    path('blog_post01/', views.blog_post01, name='blog_post01'),
    path('blog_post02/', views.blog_post02, name='blog_post02'),
    path('blog_post03/', views.blog_post03, name='blog_post03'),
    path('blog_post04/', views.blog_post04, name='blog_post04'),
    path('blog_post05/', views.blog_post05, name='blog_post05'),   
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('remove_materials/', views.remove_materials, name="remove_materials"),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('modify_user_profile/', views.modify_user_profile,
         name='modify_user_profile'),
    path('add_gln/', views.add_gln, name='add_gln'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='dash/dashboard/profile/change_password.html',
        success_url='/dash/user_profile'), name='change_password'),
    path("select2/", include("django_select2.urls")),
    path('nearby/', views.nearby, name="nearby"),
    path('admin/import_material_AT',
         views.import_material_AT, name='import_material_AT'),
    path('admin/import_material_EU',
         views.import_material_EU, name='import_material_EU'),
    #re_path(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', name='jsi18n'),
    path('contact-landfill/', views.contact_landfill, name='contact-landfill'),
]

seiketsu/seiketsu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Dash import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('dash/', include('Dash.urls'), name='dash'),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

seiketsu/Dash/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from .forms import AddGLN, AddOpeningHours, ChangeAdressData, UserForm_Deponie, UserProfileInfo_Deponie, \
    UserForm_Bauunternehmer, UserProfileInfo_Bauunternehmer, UserProfileInfo_Deponie, SearchLandfills, \
    LandfillsSearchResult
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
import django.contrib.messages as messages
from django import forms
from django.forms import formset_factory, modelformset_factory
from django.conf import settings
from django.views import generic
from django.contrib.gis.geos import fromstr
from django.contrib.gis.db.models.functions import Distance
from .models import Country, Deponie, Bauunternehmer, Materialien_AT, Materialien_EU, Opening_Hours, User_Adress, gis_Location, gln_Data
from django.contrib.auth.models import User, Group
from django.contrib.gis.geos.point import Point
import requests
import urllib.parse
from Dash.functions.parser_abfallkodex_austria import material_importer
from django.core.mail import BadHeaderError
from django.core import mail
from django.core.mail import EmailMultiAlternatives, send_mail

from pprint import pprint

DASH_NEARBY_HTML = 'dash/nearby.html'
CONTACT_LANDFILL_HTML = 'dash/contact-landfill.html'


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.EmailField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': '', 'id': 'hello'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': '',
            'id': 'hi',
        }
    ))


@login_required
def special(request):
    return HttpResponse("you are logged in")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))


def index(request):
    return render(request, 'dash/index.html')

def partner_werden(request):
    return render(request, 'dash/partner-werden.html')

def vision(request):
    return render(request, 'dash/vision.html')

def blog_overview(request):
    return render(request, 'dash/blog/blog_overview.html')

#---single blog posts, need to be done dynamically later ---#

def blog_post01(request):
    return render(request, 'dash/blog/blog_post1.html')
def blog_post02(request):
    return render(request, 'dash/blog/blog_post2.html')
def blog_post03(request):
    return render(request, 'dash/blog/blog_post3.html')
def blog_post04(request):
    return render(request, 'dash/blog/blog_post4.html')
def blog_post05(request):
    return render(request, 'dash/blog/blog_post5.html')

def register(request):
    registered = False
    user_form_deponie = UserForm_Deponie()
    profile_form_deponie = UserProfileInfo_Deponie()
    user_form_bauunternehmer = UserForm_Bauunternehmer()
    profile_form_bauunternehmer = UserProfileInfo_Bauunternehmer()

    if request.method == "POST":
        account_type = request.POST.get('account_type')
        if account_type == 'abfallbehandler':
            user_form_deponie = UserForm_Deponie(data=request.POST)
            profile_form_deponie = UserProfileInfo_Deponie(data=request.POST)

            if user_form_deponie.is_valid() and profile_form_deponie.is_valid():
                user = user_form_deponie.save()
                user.set_password(user.password)
                add_to_group = Group.objects.get(name='Abfallbehandler')
                add_to_group.user_set.add(user)
                user.save()
                profile = profile_form_deponie.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form_deponie.errors, profile_form_deponie.errors)

        elif account_type == 'bauunternehmer':
            user_form_bauunternehmer = UserForm_Bauunternehmer(
                data=request.POST)
            profile_form_bauunternehmer = UserProfileInfo_Bauunternehmer(
                data=request.POST)

            if user_form_bauunternehmer.is_valid() and profile_form_bauunternehmer.is_valid():
                user = user_form_bauunternehmer.save()
                user.set_password(user.password)
                add_to_group = Group.objects.get(name='Bauunternehmer')
                add_to_group.user_set.add(user)
                user.save()
                profile = profile_form_bauunternehmer.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form_bauunternehmer.errors,
                      profile_form_bauunternehmer.errors)

    return render(request, 'dash/registration.html', {'user_form_deponie': user_form_deponie,
                                                      'profile_form_deponie': profile_form_deponie,
                                                      'user_form_bauunternehmer': user_form_bauunternehmer,
                                                      'profile_form_bauunternehmer': profile_form_bauunternehmer,
                                                      'registered': registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/dash/dashboard')

            else:
                return HttpResponse("UPPPSSS Something went wrong")
        else:
            print("someone tried to do the old hackedy hack")
            print("Username: {}".format(username))
            return HttpResponse("Computer says no!")

    else:
        return render(request, 'dash/login.html', {})


@login_required
def dashboard(request):
    return render(request, 'dash/dashboard/dashboard.html', {})


@login_required
def user_profile(request):
    if request.method == "GET":
        user_model_data = User.objects.get(pk=request.user.id)
        user_models = [Bauunternehmer, Deponie]
        primary_adress = None
        for model in user_models:
            try:
                current_user = model.objects.get(user=request.user.id)

                if current_user:
                    break
            except:
                messages.error(request, "User Data could not be found")
        try:
            user_adress_data = User_Adress.objects.all().filter(user=request.user.id)
            for adress_item in user_adress_data:
                if adress_item.is_primary_adress is True:
                    primary_adress = adress_item
                    break
        except:
            primary_adress = None

        try:
            user_gln_data = gln_Data.objects.all().filter(user=request.user.id)
            gln_data_container = []
            for data_item in user_gln_data:
                gln_data_container.append(data_item)
        except:
            gln_data_container = None

    if request.method == "POST":

        if request.POST['delete_gln']:
            gln_to_delete = gln_Data.objects.get(id=request.POST['delete_gln'])
            opening_days_to_delete = Opening_Hours.objects.all().filter(
                location=gln_to_delete.location)
            adress_to_delete = User_Adress.objects.get(
                id=gln_to_delete.adress.id)
            gis_location_to_delete = gis_Location.objects.get(
                id=gln_to_delete.location.id)
            gln_to_delete.delete()
            opening_days_to_delete.delete()
            adress_to_delete.delete()
            gis_location_to_delete.delete()

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, 'dash/dashboard/profile/user_profile.html',
                  {'usermodel_data': user_model_data, 'usermodel_type_data': current_user,
                   'usermodel_adress_data': primary_adress, 'usermodel_gln_data': gln_data_container, })


@login_required
def modify_user_profile(request):
    if request.method == "GET":
        try:
            user_adress_data = User_Adress.objects.all().filter(user=request.user.id)
            user_model_data = User.objects.get(pk=request.user.id)
            for adress_item in user_adress_data:
                if adress_item.is_primary_adress is True:
                    primary_adress = adress_item
                    break
            update_adress_form = ChangeAdressData(instance=primary_adress)
        except:
            update_adress_form = ChangeAdressData()

    if request.method == "POST":
        # user_adress = User_Adress.objects.get(user=)
        user_adress_form = ChangeAdressData(data=request.POST)
        user_model_data = User.objects.get(pk=request.user.id)
        if user_adress_form.is_valid():
            current_adress_form = user_adress_form.save(commit=False)
            current_adress_form.is_primary_adress = True
            current_adress_form.user = request.user
            current_adress_form.save()
            user_model_data.first_name=request.POST['company_name']
            user_model_data.save()
           
        return HttpResponseRedirect('/dash/user_profile')
    
    

    return render(request, 'dash/dashboard/profile/modify_user_profile.html', {'adress_form': update_adress_form, 'user_model_data':user_model_data})


@login_required
def remove_materials(request):
    material_ids_to_remove = request.POST.getlist('materials_to_remove[]')

seiketsu/templates/dash/base.html
<!DOCTYPE html> {%load static%}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>

<head>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Revitalyze</title>
    {% comment %} <link rel="icon" type="image/x-icon" href="{% static '/images/icons/revi-favi.png' %}"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Revitalyze" />
    <meta name="keywords" content="revitalyze rethink rebuild recycle landfill deponie construction waste bauschutt umwelt enviroment umweltschutz digitalisierung wastehandling" />
    <meta name="author" content="Revitalyze" />
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
 
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700,900' rel='stylesheet' type='text/css'>

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300&family=Montserrat:wght@100;400;900&family=Mulish:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppins:wght@300&family=Sacramento&family=Ubuntu:wght@300;400;500;700&display=swap"
        rel="stylesheet">

    <!-- Animate.css 
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">-->
    <!-- Icomoon Icon Fonts
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">-->
    <!-- Simple Line Icons 
    <link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">-->
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!--<link rel="stylesheet" href="{% static 'css/style.css' %}">-->

    <!--bootstrap CDN-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>

    <!-- Modernizr JS -->

    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <script src="{% static 'js/jquery.validate.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/styles-website.css' %}">
    </head>

<body>
    <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <div id="fh5co-page" style="">
        <header style="height: 100px; display: flex; position: relative; z-index: 10000000;">
            <div class="container navbar navbar-expand-sm justify-content-between">
                <div class="header-inner px-3 px-sm-0 w-100 landing-header-grid-container">
                    <a href="/" class="d-flex align-items-center" style="font-size: 0;"><img class="header-logo" src="{% static '/images/logos/2021_10_08_REVITALYZE_Logo_RZ.png' %}"></a>
                   {% comment %} <a href="/" style="font-size: 0;"><svg viewBox="35 25 150 100"> <image href="{% static '/images/logos/standard.svg' %}"></svg></a> {% endcomment %}
                    <nav role="navigation" class="navbar navbar-background-responsive navbar-expand-sm bg-transparent justify-content-between">
                        <div class="container-fluid justify-content-end">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="nav navbar-container navbar-nav d-flex">
                                    <li class="px-2"><a class="nav-item nav-link" href="{%url 'Dash:nearby'%}">Suche</a></li>
                                    <li class="px-2"><a class="nav-item nav-link" href="{%url 'Dash:partner_werden'%}">Partner Werden</a></li>
                                    <li class="px-2"><a class="nav-item nav-link" href="{%url 'Dash:vision'%}">Über uns</a></li>
                                    <li class="px-2"><a class="nav-item nav-link" href="{%url 'Dash:blog_overview'%}">Blog</a></li>

                                    <li class="px-2"><a class="nav-item nav-link" href="{%url 'Dash:register'%}">Register</a></li>
                                    {% if user.is_authenticated %}
                                    <li class="px-2"> <a class="nav-item nav-link" href="{%url 'logout'%}">Logout</a></li>
                                    <li class="px-2"> <a class="nav-item nav-link" href="{%url 'Dash:dashboard'%}">Dashboard</a></li>
                                    {%else%}
                                    <li class="px-2 navbar-element-login"><a class="nav-item nav-link" href="{% url 'Dash:user_login'%}">Login</a></li>
                                    {%endif%}


                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </header>
            {% block body_block %} {% endblock %}
            {% include 'dash/script-block.html'  %}
        <footer id="fh5co-footer" role="contentinfo">
            {% block footer_block %}
            {% include 'dash/footer.html'  %}
            {% endblock %}
        </footer>


</body>

</html>

seiketsu/templates/dash/login.html
{%extends 'dash/base.html'%} {%block body_block%}

<div class='jumbotron' style="height: 31.8vw">
    <div class="d-flex flex-column h-100 justify-content-center align-items-center">
    <div class="p-5" style="border-radius: 6px; box-shadow: 5px 10px 18px #888888; background-color: transparent;">
    <h1 class="pb-3">Willkommen zurück!</h1>
        <form action="{% url 'Dash:user_login'%}" method="post">
            {%csrf_token%}
            <div class="d-flex flex-column">
            <label for="username">Username:</label>
            <input class="form-control" type="text" name="username" placeholder="Enter Username">
            <div class="py-3">
                <label for="password">Password</label>
                <input class="form-control" type="password" name="password" value="">
            </div>
            <input type="submit" class="btn w-50 mt-2 align-self-center btn-primary" name="" value="Login">
            </div>
        </form>
        </div>
    </div>
    {% comment %} <div style="position: relative;">
                <?xml version="1.0" encoding="utf-8"?>      
                <svg version="1.1" id="Ebene_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                    viewBox="0 0 841.9 595.3" style="enable-background:new 0 0 841.9 595.3;  position: absolute; margin-left: -20em; margin-top: -64em; z-index: -10; width: 120em;" xml:space="preserve">
                    <style type="text/css">
                    .st0{fill:#C2121E;
                    opacity: 0.05;}
                    </style>
                    <g>
                    <path class="st0" d="M420,133.3c-62.2,0-116.5,34.6-144.6,85.6c-0.2,0.3-0.3,0.6-0.5,0.8c-0.6,1.2-1.2,2.4-1.9,3.5
                        c-0.6,1.2-1.2,2.4-1.8,3.6c-0.5,1-0.9,1.9-1.4,2.9c-0.2,0.5-0.5,1-0.7,1.5c-0.4,1-0.8,1.9-1.2,2.9c-0.6,1.2-1.1,2.5-1.5,3.7
                        c-0.9,2.3-1.8,4.6-2.6,7c-0.1,0.4-0.3,0.9-0.4,1.3c-0.2,0.6-0.4,1.2-0.6,1.7h0h16h14.8H425c24.9,0,45.3,21.2,42.6,45.9
                        c-1.4,12.5-8.3,23.2-18.2,29.9c-5.2,3.5-11.1,5.8-17.6,6.6c-1.7,0.2-3.5,0.3-5.3,0.3c0,0-34.8,0.2-34.7,0.3l28.2,28.3l60.7,60.8
                        l0.1,0.1c-1.3,0.7-2.6,1.3-3.9,1.9c-1.5,0.7-2.9,1.3-4.4,1.9c-0.6,0.3-1.2,0.5-1.8,0.8c-1.2,0.5-2.3,0.9-3.5,1.4
                        c-15.1,5.5-30.9,8.4-47.1,8.4c-14.1,0-27.6-2.1-40.4-6.1c-2.1-0.7-4.2-1.4-6.3-2.1c-2.1-0.8-4.2-1.6-6.2-2.4c-2-0.9-4-1.8-6-2.7
                        c-7.9-3.8-15.4-8.4-22.4-13.6c-1.7-1.3-3.5-2.6-5.1-4c-3.4-2.8-6.6-5.7-9.7-8.8c-1.2-1.2-2.4-2.4-3.5-3.7c-0.3-0.3-0.6-0.7-1-1
                        c-1-1.1-1.9-2.2-2.9-3.3c-0.2-0.3-0.4-0.5-0.7-0.8c-0.8-1-1.7-2.1-2.5-3.1c-0.1-0.1-0.2-0.2-0.3-0.3c-0.4-0.5-0.8-1-1.2-1.6
                        c-0.9-1.2-1.8-2.4-2.7-3.6c-0.6-0.9-1.2-1.8-1.9-2.7c-1.2-1.8-2.4-3.7-3.5-5.5c-1.7-2.8-3.3-5.7-4.8-8.6c-1-1.9-1.9-3.9-2.9-5.9
                        c-0.9-2-1.8-4-2.6-6.1c-0.8-2.1-1.6-4.1-2.3-6.2c-0.6-1.9-1.2-3.8-1.8-5.7c-0.4-1.3-0.8-2.6-1.1-3.9c-0.1-0.3-0.2-0.6-0.2-0.9
                        c-0.4-1.5-0.8-3.1-1.1-4.6c-0.1-0.3-0.1-0.7-0.2-1c-0.3-1.5-0.6-2.9-0.8-4.4c-1.1-6.4-1.7-12.9-1.9-19.5c0-1.2-0.1-2.4-0.1-3.5
                        c0-1.2,0-2.4,0.1-3.5c0.1-2.3,0.2-4.6,0.3-6.9c0.1-0.9,0.1-1.7,0.2-2.6c0.3-2.8,0.6-5.6,1-8.3h-29.3c-0.1,0.3-0.1,0.6-0.1,0.8
                        c-0.2,1.6-0.4,3.2-0.5,4.8c-0.2,1.7-0.3,3.4-0.4,5.1v0.2c-0.1,1.6-0.2,3.2-0.2,4.8c-0.1,1.9-0.1,3.8-0.1,5.8c0,1.9,0,3.9,0.1,5.8
                        c0,1.6,0.1,3.2,0.2,4.8v0.2c0.1,1.7,0.2,3.4,0.4,5.1c0.1,1.6,0.3,3.2,0.5,4.8c0.2,1.5,0.4,3,0.6,4.6c0.1,1,0.3,1.9,0.5,2.8
                        c0.1,0.7,0.2,1.4,0.4,2.1c0.1,0.8,0.3,1.7,0.5,2.5c0.8,4.2,1.9,8.4,3,12.6c0.3,1.2,0.7,2.4,1.1,3.6c0.5,1.6,1,3.3,1.6,4.9
                        c0.3,1,0.7,2.1,1.1,3.1c0.9,2.5,1.9,5,3,7.5c0.3,0.8,0.6,1.5,1,2.2c0.4,1,0.8,1.9,1.3,2.9c0.4,0.9,0.8,1.9,1.3,2.8c0.5,1,1,2,1.5,3
                        c0.6,1.2,1.2,2.4,1.9,3.5c1.2,2.3,2.6,4.6,4,6.9c1.4,2.3,2.8,4.5,4.3,6.7c4.4,6.6,9.4,12.8,14.7,18.7c0.7,0.8,1.5,1.6,2.2,2.4
                        c1.4,1.5,2.8,2.9,4.2,4.3c0.6,0.6,1.2,1.2,1.9,1.8c7.6,7.3,16,13.9,24.9,19.6c1,0.6,2,1.3,3,1.9c3.5,2.1,7.1,4.1,10.8,6
                        c1.2,0.6,2.4,1.2,3.6,1.8c1.6,0.8,3.2,1.5,4.8,2.2c0.8,0.4,1.7,0.7,2.5,1.1c3.9,1.7,7.9,3.2,12,4.6c0.8,0.3,1.6,0.5,2.4,0.8
                        c6.4,2,12.9,3.7,19.6,4.9c0.8,0.2,1.6,0.3,2.4,0.4c0.9,0.1,1.8,0.3,2.6,0.4c1.4,0.2,2.8,0.4,4.2,0.6c1.7,0.2,3.4,0.4,5.1,0.6
                        c0.1,0,0.2,0,0.3,0c1.6,0.1,3.2,0.3,4.8,0.4h0.2c1.6,0.1,3.1,0.2,4.7,0.2c1.9,0.1,3.9,0.1,5.8,0.1c19.6,0,38.9-3.4,57.2-10.2
                        c2.2-0.8,4.4-1.7,6.6-2.6c1.4-0.6,2.7-1.1,4-1.7c0.7-0.3,1.5-0.7,2.2-1c1.1-0.5,2.3-1.1,3.4-1.6c1-0.5,1.9-1,2.8-1.5
                        c1-0.5,2-1.1,3-1.6c1-0.6,2-1.1,3-1.7c0.8-0.5,1.6-0.9,2.4-1.4c1.3-0.7,2.5-1.5,3.7-2.3c0.3-0.2,0.5-0.3,0.8-0.5
                        c0.5-0.3,0.9-0.6,1.4-0.9c0.4-0.2,0.8-0.5,1.1-0.7c1.6-1,3.1-2.1,4.6-3.2c1.5-1,2.9-2.1,4.3-3.2c0.4-0.3,0.9-0.7,1.3-1
                        c0,0,0.1-0.1,0.1-0.1c1.4-1.1,2.8-2.2,4.1-3.4c0.1-0.1,0.1-0.1,0.2-0.1l-20.6-20.6v0l0,0l-50.2-50.2c-0.1-0.1-0.1-0.2,0-0.2
                        c19.9-9.1,35-27.2,39.7-49.1c1.1-4.8,1.6-9.8,1.6-15c0-15.3-4.9-29.4-13.2-40.9c-12.8-17.8-33.6-29.4-57.2-29.4H309.7
                        c0.9-1.3,1.9-2.5,2.8-3.7c0.8-1.1,1.7-2.1,2.6-3.2c25-30.3,62.7-49.6,105-49.6c75,0,136,61,136,136c0,31.6-11.1,61.5-30.1,85.1
                        l13.5,13.5l0,0v0l7.1,7.1C570.8,375,585,337.7,585,298.3C585,207.3,511,133.3,420,133.3L420,133.3z"/>
                    </g>
                </svg>
            </div> {% endcomment %}
</div>

{%endblock%}