seiketsu/Dash/urls.py
from . import views
from django.urls import path, include

from django.contrib.auth import views as auth_views

app_name = 'Dash'

urlpatterns = [
    # path('loged_in', views.index),
    #path('', views.login),
    path('partner-werden/', views.partner_werden, name='partner_werden'),
    path('vision/', views.vision, name='vision'),
    path('blog/', views.blog_overview, name='blog_overview'), 
    path('blog_post01/', views.blog_post01, name='blog_post01'),
    path('blog_post02/', views.blog_post02, name='blog_post02'),
    path('blog_post03/', views.blog_post03, name='blog_post03'),
    path('blog_post04/', views.blog_post04, name='blog_post04'),
    path('blog_post05/', views.blog_post05, name='blog_post05'),   
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('remove_materials/', views.remove_materials, name="remove_materials"),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('modify_user_profile/', views.modify_user_profile,
         name='modify_user_profile'),
    path('add_gln/', views.add_gln, name='add_gln'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='dash/dashboard/profile/change_password.html',
        success_url='/dash/user_profile'), name='change_password'),
    path("select2/", include("django_select2.urls")),
    path('nearby/', views.nearby, name="nearby"),
    path('admin/import_material_AT',
         views.import_material_AT, name='import_material_AT'),
    path('admin/import_material_EU',
         views.import_material_EU, name='import_material_EU'),
    #re_path(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', name='jsi18n'),
    path('contact-landfill/', views.contact_landfill, name='contact-landfill'),
]

seiketsu/seiketsu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Dash import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('dash/', include('Dash.urls'), name='dash'),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

seiketsu/Dash/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from .forms import AddGLN, AddOpeningHours, ChangeAdressData, UserForm_Deponie, UserProfileInfo_Deponie, \
    UserForm_Bauunternehmer, UserProfileInfo_Bauunternehmer, UserProfileInfo_Deponie, SearchLandfills, \
    LandfillsSearchResult
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
import django.contrib.messages as messages
from django import forms
from django.forms import formset_factory, modelformset_factory
from django.conf import settings
from django.views import generic
from django.contrib.gis.geos import fromstr
from django.contrib.gis.db.models.functions import Distance
from .models import Country, Deponie, Bauunternehmer, Materialien_AT, Materialien_EU, Opening_Hours, User_Adress, gis_Location, gln_Data
from django.contrib.auth.models import User, Group
from django.contrib.gis.geos.point import Point
import requests
import urllib.parse
from Dash.functions.parser_abfallkodex_austria import material_importer
from django.core.mail import BadHeaderError
from django.core import mail
from django.core.mail import EmailMultiAlternatives, send_mail

from pprint import pprint

DASH_NEARBY_HTML = 'dash/nearby.html'
CONTACT_LANDFILL_HTML = 'dash/contact-landfill.html'


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.EmailField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': '', 'id': 'hello'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': '',
            'id': 'hi',
        }
    ))


@login_required
def special(request):
    return HttpResponse("you are logged in")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('user_login'))


def index(request):
    return render(request, 'dash/index.html')

def partner_werden(request):
    return render(request, 'dash/partner-werden.html')

def vision(request):
    return render(request, 'dash/vision.html')

def blog_overview(request):
    return render(request, 'dash/blog/blog_overview.html')

#---single blog posts, need to be done dynamically later ---#

def blog_post01(request):
    return render(request, 'dash/blog/blog_post1.html')
def blog_post02(request):
    return render(request, 'dash/blog/blog_post2.html')
def blog_post03(request):
    return render(request, 'dash/blog/blog_post3.html')
def blog_post04(request):
    return render(request, 'dash/blog/blog_post4.html')
def blog_post05(request):
    return render(request, 'dash/blog/blog_post5.html')

def register(request):
    registered = False
    user_form_deponie = UserForm_Deponie()
    profile_form_deponie = UserProfileInfo_Deponie()
    user_form_bauunternehmer = UserForm_Bauunternehmer()
    profile_form_bauunternehmer = UserProfileInfo_Bauunternehmer()

    if request.method == "POST":
        account_type = request.POST.get('account_type')
        if account_type == 'abfallbehandler':
            user_form_deponie = UserForm_Deponie(data=request.POST)
            profile_form_deponie = UserProfileInfo_Deponie(data=request.POST)

            if user_form_deponie.is_valid() and profile_form_deponie.is_valid():
                user = user_form_deponie.save()
                user.set_password(user.password)
                add_to_group = Group.objects.get(name='Abfallbehandler')
                add_to_group.user_set.add(user)
                user.save()
                profile = profile_form_deponie.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form_deponie.errors, profile_form_deponie.errors)

        elif account_type == 'bauunternehmer':
            user_form_bauunternehmer = UserForm_Bauunternehmer(
                data=request.POST)
            profile_form_bauunternehmer = UserProfileInfo_Bauunternehmer(
                data=request.POST)

            if user_form_bauunternehmer.is_valid() and profile_form_bauunternehmer.is_valid():
                user = user_form_bauunternehmer.save()
                user.set_password(user.password)
                add_to_group = Group.objects.get(name='Bauunternehmer')
                add_to_group.user_set.add(user)
                user.save()
                profile = profile_form_bauunternehmer.save(commit=False)
                profile.user = user
                profile.save()
                registered = True
            else:
                print(user_form_bauunternehmer.errors,
                      profile_form_bauunternehmer.errors)

    return render(request, 'dash/registration.html', {'user_form_deponie': user_form_deponie,
                                                      'profile_form_deponie': profile_form_deponie,
                                                      'user_form_bauunternehmer': user_form_bauunternehmer,
                                                      'profile_form_bauunternehmer': profile_form_bauunternehmer,
                                                      'registered': registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/dash/dashboard')

            else:
                return HttpResponse("UPPPSSS Something went wrong")
        else:
            print("someone tried to do the old hackedy hack")
            print("Username: {}".format(username))
            return HttpResponse("Computer says no!")

    else:
        return render(request, 'dash/login.html', {})


@login_required
def dashboard(request):
    return render(request, 'dash/dashboard/dashboard.html', {})


@login_required
def user_profile(request):
    if request.method == "GET":
        user_model_data = User.objects.get(pk=request.user.id)
        user_models = [Bauunternehmer, Deponie]
        primary_adress = None
        for model in user_models:
            try:
                current_user = model.objects.get(user=request.user.id)

                if current_user:
                    break
            except:
                messages.error(request, "User Data could not be found")
        try:
            user_adress_data = User_Adress.objects.all().filter(user=request.user.id)
            for adress_item in user_adress_data:
                if adress_item.is_primary_adress is True:
                    primary_adress = adress_item
                    break
        except:
            primary_adress = None

        try:
            user_gln_data = gln_Data.objects.all().filter(user=request.user.id)
            gln_data_container = []
            for data_item in user_gln_data:
                gln_data_container.append(data_item)
        except:
            gln_data_container = None

    if request.method == "POST":

        if request.POST['delete_gln']:
            gln_to_delete = gln_Data.objects.get(id=request.POST['delete_gln'])
            opening_days_to_delete = Opening_Hours.objects.all().filter(
                location=gln_to_delete.location)
            adress_to_delete = User_Adress.objects.get(
                id=gln_to_delete.adress.id)
            gis_location_to_delete = gis_Location.objects.get(
                id=gln_to_delete.location.id)
            gln_to_delete.delete()
            opening_days_to_delete.delete()
            adress_to_delete.delete()
            gis_location_to_delete.delete()

            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, 'dash/dashboard/profile/user_profile.html',
                  {'usermodel_data': user_model_data, 'usermodel_type_data': current_user,
                   'usermodel_adress_data': primary_adress, 'usermodel_gln_data': gln_data_container, })


@login_required
def modify_user_profile(request):
    if request.method == "GET":
        try:
            user_adress_data = User_Adress.objects.all().filter(user=request.user.id)
            user_model_data = User.objects.get(pk=request.user.id)
            for adress_item in user_adress_data:
                if adress_item.is_primary_adress is True:
                    primary_adress = adress_item
                    break
            update_adress_form = ChangeAdressData(instance=primary_adress)
        except:
            update_adress_form = ChangeAdressData()

    if request.method == "POST":
        # user_adress = User_Adress.objects.get(user=)
        user_adress_form = ChangeAdressData(data=request.POST)
        user_model_data = User.objects.get(pk=request.user.id)
        if user_adress_form.is_valid():
            current_adress_form = user_adress_form.save(commit=False)
            current_adress_form.is_primary_adress = True
            current_adress_form.user = request.user
            current_adress_form.save()
            user_model_data.first_name=request.POST['company_name']
            user_model_data.save()
           
        return HttpResponseRedirect('/dash/user_profile')
    
    

    return render(request, 'dash/dashboard/profile/modify_user_profile.html', {'adress_form': update_adress_form, 'user_model_data':user_model_data})


@login_required
def remove_materials(request):
    material_ids_to_remove = request.POST.getlist('materials_to_remove[]')

seiketsu/templates/dash/dashboard/dashboard.html
{% load static%}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">


<head>
    <title>Revitalyze - Dashboard</title>
    <!-- HTML5 Shim and Respond.js IE9 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
     <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
     <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
     <![endif]-->

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">

    <!--Bootstrap Icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <!--Bootstrap 5 CDN-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Style.css -->
    <link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/jquery.validate.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/revitalyze-main.js' %}"></script>
    <script type="application/json" src="/admin/jsi18n/"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script> 
<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!-- google maps-->
    <script src="{%static 'js/init_maps.js'%}"></script>
</head>

<body class="sidebar-mini fixed">
   
    <div class="wrapper">
       
        <aside class="main-sidebar hidden-print ">

            <!-- <img src="{% static 'images/logos/logo_red.svg' %}"> -->

            <section class="sidebar" id="sidebar-scroll">
                <!-- Sidebar Menu-->
                <ul class="sidebar-menu nav flex-column">
                 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Dash:dashboard'%}">
                            <i class="bi bi-speedometer2"></i><span> Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'Dash:user_profile'%}"><i class="bi bi-file-person"></i> Profil</a>
                    </li>
                    <li class="nav-item">
                        <li> <a class="nav-link" href="{%url 'logout'%}">Logout</a></li>
                    </li>
                </ul>
            </section>
        </aside> 
        <div class="container m-0 p-0">
            {% block dashboard_body_block%}

            <div class="p-5"><h1>Willkommen in Ihrem Revitalyze-Account!</h1></div>

            {% endblock %}
        </div>
    </div>

</body>

</html>