seiketsu/Dash/urls.py
from . import views
from django.urls import path, include

from django.contrib.auth import views as auth_views

app_name = 'Dash'

urlpatterns = [
    # path('loged_in', views.index),
    #path('', views.login),
    path('partner-werden/', views.partner_werden, name='partner_werden'),
    path('vision/', views.vision, name='vision'),
    path('blog/', views.blog_overview, name='blog_overview'), 
    path('blog_post01/', views.blog_post01, name='blog_post01'),
    path('blog_post02/', views.blog_post02, name='blog_post02'),
    path('blog_post03/', views.blog_post03, name='blog_post03'),
    path('blog_post04/', views.blog_post04, name='blog_post04'),
    path('blog_post05/', views.blog_post05, name='blog_post05'),   
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('remove_materials/', views.remove_materials, name="remove_materials"),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('modify_user_profile/', views.modify_user_profile,
         name='modify_user_profile'),
    path('add_gln/', views.add_gln, name='add_gln'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='dash/dashboard/profile/change_password.html',
        success_url='/dash/user_profile'), name='change_password'),
    path("select2/", include("django_select2.urls")),
    path('nearby/', views.nearby, name="nearby"),
    path('admin/import_material_AT',
         views.import_material_AT, name='import_material_AT'),
    path('admin/import_material_EU',
         views.import_material_EU, name='import_material_EU'),
    #re_path(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', name='jsi18n'),
    path('contact-landfill/', views.contact_landfill, name='contact-landfill'),
]

seiketsu/seiketsu/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from Dash import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('dash/', include('Dash.urls'), name='dash'),
    path('admin/', admin.site.urls),
    path("select2/", include("django_select2.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

seiketsu/Dash/models.py
from django.contrib.auth.models import User
from django.contrib.gis.db import models as gisModels
from django.db import models
from django.db.models.fields.related import ForeignKey
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.


class DeponieTyp(models.Model):
    name = models.CharField(max_length=25)


class Sonderbedingungen(models.Model):
    name = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=256)
    phoneCode = models.IntegerField()

    def __str__(self):
        return self.name


class Deponie(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    uid = models.CharField(max_length=265, null=True)
    deponieTyp = models.ManyToManyField(DeponieTyp, blank=True)

    def __str__(self):
        return super().__str__()


class Bauunternehmer(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    uid = models.CharField(max_length=20, null=True)

    def __str__(self):
        return super().__str__()


class Bill(models.Model):
    billNumber = models.IntegerField()
    deponie = models.ForeignKey(Deponie, on_delete=models.PROTECT)
    bauunternehmer = models.ForeignKey(
        Bauunternehmer, on_delete=models.PROTECT)


class User_Adress(models.Model):
    is_primary_adress = models.BooleanField(default=False)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    zipCode = models.IntegerField(null=True)
    city = models.CharField(max_length=256, null=True)
    street = models.CharField(max_length=256, null=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, null=True)
    phone = PhoneNumberField(null=True, blank=True)

    def __str__(self):
        return "%s %s %s" % (self.street, self.city, self.country)


class gis_Location(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    location = gisModels.PointField(null=True)

    def __str__(self):
        return str(self.location)


class Opening_Hours(models.Model):
    WEEKDAYS = [
        (0, _("Monday")),
        (1, _("Tuesday")),
        (2, _("Wednesday")),
        (3, _("Thursday")),
        (4, _("Friday")),
        (5, _("Saturday")),
        (6, _("Sunday")),
    ]
    weekday = models.PositiveSmallIntegerField(choices=WEEKDAYS)
    location = models.ForeignKey(
        gis_Location, on_delete=models.CASCADE, null=True)
    opening_hours_am_from = models.TimeField(null=True, blank=True)
    opening_hours_am_to = models.TimeField(null=True, blank=True)
    opening_hours_pm_from = models.TimeField(null=True, blank=True)
    opening_hours_pm_to = models.TimeField(null=True, blank=True)

    def __str__(self):
        return str(self.WEEKDAYS[self.weekday])


class Materialien_AT(models.Model):
    # fields of the austrian garbage-matrix
    Gueltigkeitsbeginn = models.DateTimeField(null=True, blank=True)
    Gueltigkeitsende = models.DateTimeField(null=True, blank=True)
    GTIN = models.BigIntegerField(null=True, blank=True)
    Abfallspezifizierung = models.IntegerField(null=True, blank=True)
    Abfallschluesselnummer = models.IntegerField(null=True, blank=True)
    Gefaehrlich = models.CharField(max_length=256, null=True)
    Bezeichnung = models.TextField(null=True, blank=True)
    Beschreibung = models.TextField(null=True, blank=True)
    Schlüsselnummer_falls_gefaehrlich = models.TextField(null=True, blank=True)
    Schluesselnummer_falls_ausgestuft_bzw_nicht_gefaehrlich = models.TextField(
        null=True, blank=True)
    Anmerkung = models.TextField(null=True, blank=True)
    Rechtliches_Inkrafttreten = models.DateTimeField(null=True, blank=True)
    Rechtliches_Ausserkrafttreten = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        if self.Abfallspezifizierung:
            if self.Gefaehrlich:
                return "Schlüsselnummer: "+str(self.Abfallschluesselnummer) + ' | Spezifikation: '+str(self.Abfallspezifizierung) + ' | ' + str(self.Bezeichnung)+' | Gefährlich'
            else:
                return 'Schlüsselnummer: ' + str(self.Abfallschluesselnummer) + ' | Spezifikation: '+str(self.Abfallspezifizierung) + ' | ' + str(self.Bezeichnung)
        else:
            if self.Gefaehrlich:
                return 'Schlüsselnummer: '+str(self.Abfallschluesselnummer) + ' | Spezifikation: ' + str(self.Bezeichnung)+' | Gefährlich'
            else:
                return 'Schlüsselnummer: '+str(self.Abfallschluesselnummer) + ' | Spezifikation: ' + str(self.Bezeichnung)


class Materialien_EU(models.Model):
    # fields of the european garbage-matrix
    Abfallschluesselnummer = models.TextField(null=True, blank=True)
    Gefaehrlich = models.BooleanField(blank=True, null=True)
    Bezeichnung = models.TextField(null=True, blank=True)

    def __str__(self):
        if self.Gefaehrlich:
            return 'Schlüsselnummer: '+str(self.Abfallschluesselnummer) + ' | ' + str(self.Bezeichnung)+' | Gefährlich'
        else:
            return 'Schlüsselnummer: '+str(self.Abfallschluesselnummer) + ' | ' + str(self.Bezeichnung)


class Preisliste(models.Model):
    preisProTonne = MoneyField(
        max_digits=14, decimal_places=2, default_currency='EUR')
    deponie = models.ForeignKey(Deponie, on_delete=models.CASCADE)
    material_at = models.ManyToManyField(
        Materialien_AT, related_name="pricelist", symmetrical=False, blank=True)
    material_eu = models.ManyToManyField(
        Materialien_EU, related_name="pricelist", symmetrical=False, blank=True)


class gln_Data(models.Model):  # standort an dem müll abgeladen werden kann
    gln = models. BigIntegerField(null=True)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    location = models.ForeignKey(
        gis_Location, on_delete=models.CASCADE, null=True, blank=True)
    adress = ForeignKey(User_Adress, models.SET_NULL, null=True, blank=True)
    min_amount_in_t = models.IntegerField(null=True)
    special_conditions = models.ManyToManyField(Sonderbedingungen, blank=True)
    material_at = models.ManyToManyField(
        Materialien_AT, related_name="gln_data", symmetrical=False, blank=True)
    material_eu = models.ManyToManyField(
        Materialien_EU, related_name="gln_data", symmetrical=False, blank=True)

    def __str__(self):
        return str(self.gln)


class Order(models.Model):
    date = models.DateTimeField()
    deponie = models.ForeignKey(Deponie, on_delete=models.PROTECT)
    bauunternehmer = models.ForeignKey(
        Bauunternehmer, on_delete=models.PROTECT)
    bill_nr = models.ForeignKey(Bill, on_delete=models.PROTECT)
    material_at = models.ManyToManyField(
        Materialien_AT, related_name="order", symmetrical=False, blank=True)
    material_eu = models.ManyToManyField(
        Materialien_EU, related_name="order", symmetrical=False, blank=True)

    def __str__(self):
        return str(self.bill_nr)

seiketsu/templates/dash/dashboard/profile/add_gln.html
{% extends 'dash/dashboard/dashboard.html' %} {% load crispy_forms_tags %} {% block dashboard_body_block%}

<div class="container p-5">

    <div class="row py-2">
        <div class="col-6 col-sm-3">
            <h4>Standortdaten:</h4>
        </div>
    </div>
    <form method="post" id="gln-form" enctype="multipart/form-data">
        {%csrf_token%}
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>GLN-Nummer</b>
            </div>
            <div class="col-6 col-sm-3">
                {{gln_form.gln|as_crispy_field}}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Land</b>
            </div>
            <div class="col-6 col-sm-3">
                {{adress_form_gln.country|as_crispy_field}}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Stadt</b>
            </div>
            <div class="col-6 col-sm-3">
                {{adress_form_gln.city|as_crispy_field}}
            </div>
        </div>

        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Postleitzahl</b>
            </div>
            <div class="col-6 col-sm-3">
                {{adress_form_gln.zipCode|as_crispy_field}}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Straße</b>
            </div>
            <div class="col-6 col-sm-3">
                {{adress_form_gln.street|as_crispy_field}}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Telefon</b>
            </div>
            <div class="col-6 col-sm-3">
                {{adress_form_gln.phone|as_crispy_field}}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Sonderbedingungen</b>
            </div>
            <div class="col-6 col-sm-3">
                {{gln_form.special_conditions|as_crispy_field}}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Mindestabgabemenge in Tonnen</b>
            </div>
            <div class="col-6 col-sm-3">
                {{gln_form.min_amount_in_t|as_crispy_field}}
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Welchen Abfall möchten sie annehmen?</b>
            </div>
            <div class="row py-2">
                <div class="pb-3"><b>Materialien hinzufügen:</b></div>
                <div class="col-6 d-flex">
                    <div class="col pr-3 pb-3"> <input type="radio" class="form-check-input" name="codex-radio"  id="checkbox_AT" value="AT-codex"> Österreichischer Abfallcodex </div>
                    <div class="col px-3 pb-3"> <input type="radio" class="form-check-input" name="codex-radio" id="checkbox_EU" value="EU-codex"> Europäischer Abfallcodex </div>
                {{ gln_form.media.js }}
                
            </div>
        <div class="row" id="picker_material_at">
                    {{ gln_form.material_at }}                 
                </div>
                <div class="row" id="picker_material_eu">
                    {{ gln_form.material_eu }}                 
                </div>
        </div>
        <div class="row py-2">
            <div class="col-6 col-sm-3">
                <b>Öffnungszeiten</b>
            </div>
        </div>
        <div class="row py-2">
            <div class="col-6 ">
                {% include "./business_hours.html" %}
            </div>
        </div>
        <input type="hidden" name="gln_id" value="{{gln_id}}" />
        <input type="hidden" name="materials-for-gln" id="materials-for-gln" value="" />
        <input type="hidden" name="material-country" id="material-country" value="" />
        
        <div class="row pt-4 pb-2">
            <div class="col-8 col-sm-6">
              <button type="submit" id="submit-gln-form" class="btn btn-primary ">GLN-Standort hinzufügen</button> {{ field.errors }}
  
            </div>
        </div>
        
    </form>
    <form class="">
        <input type="button" value="zurück" class="btn btn-primary " onclick="history.back()">
    </form>
</div>

<script>
    $(document).ready(function() { 
        
        $(picker_material_at).hide()
        $(picker_material_eu).hide()
        
        $('input[type=radio][name=codex-radio]').change(function() {
            if (this.value == 'AT-codex') {
                $(picker_material_eu).hide()
                $(picker_material_at).show()
 
            } else if (this.value == 'EU-codex') {
                $(picker_material_at).hide()
                $(picker_material_eu).show()
            }
        })

        $('#submit-gln-form').click(function(event){
            event.preventDefault();
            if ($('input[name=codex-radio]:checked').val() === "AT-codex"){
                $('#materials-for-gln').val($('#id_material_at').val());
            $('#gln-form').submit()
            }else if($('input[name=codex-radio]:checked').val() === "EU-codex"){
                $('#materials-for-gln').val($('#id_material_eu').val());
                $('#gln-form').submit()
            }else{
                $('#gln-form').submit()
            }
        })

 /*$('input[type=radio][name=codex-radio]').change(function() {
        $('#tags').empty();
        if (this.value == 'AT-codex') {
             let idCounter=0;
             var availableTags_AT = []
                {% for material in material_at %}
                    availableTags_AT.push({
                        id: {{material.id}},
                        text:
                        {% if material.Gefaehrlich %}       
                            "Bezeichnung (AT): " +"{{material.Bezeichnung}} "+ "Schlüsselnummer (AT): " +"{{material.Abfallschluesselnummer}}" + " Gefährlich"
                        {% else %}
                             "Bezeichnung (AT): " +"{{material.Bezeichnung}} "+ "Schlüsselnummer (AT): " +"{{material.Abfallschluesselnummer}}"
                        {% endif %}
                    },)
                    {% endfor %}
                


        $('#tags').select2({
            minimumInputLength: 3,
            data: availableTags_AT,
            closeOnSelect: false,
            placeholder: "Material eingeben",
            allowClear: true
        });
        } else if (this.value == 'EU-codex') {
            $('#tags').empty();
        
           var availableTags_EU = []
            {% for material in material_eu %}
                availableTags_EU.push({
                    id: {{material.id}},
                    text: "Bezeichnung (EU): " +"{{material.Bezeichnung}} "+ "Schlüsselnummer (EU): " +"{{material.Abfallschluesselnummer}}"
            
                },)
                {% endfor %}
     
        $('#tags').select2({
            minimumInputLength: 2,
            data: availableTags_EU,
            closeOnSelect: false,
            placeholder: "Material eingeben",
            allowClear: true
        });
        }
    });*/

    });
</script>

{% endblock %}

seiketsu/templates/dash/dashboard/profile/business_hours.html
{% load crispy_forms_tags %}

<div class="grid-container-days">
    <div class="grid-container-hours">

    <div class="grid-container-vormittag">Vormittag</div>
    <div class="grid-container-nachmittag">Nachmittag</div>
    </div>
    <div class="grid-container-hours">
        {{ hours_form.management_form }}
        <div class="grid-item">
            <div class="weekdays-displayed">Montag</div>
        </div>
        {{ hours_form.0.id }}
        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.0.opening_hours_am_from }}
        </div>
 
        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.0.opening_hours_am_to}}
        </div>

        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.0.opening_hours_pm_from }}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.0.opening_hours_pm_to}}
        </div>
    </div>

    <div class="grid-container-hours">
        
        <div class="grid-item">
            <div class="weekdays-displayed">Dienstag</div>
        </div>
        {{ hours_form.1.id }}
        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.1.opening_hours_am_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.1.opening_hours_am_to}}
        </div>

        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.1.opening_hours_pm_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.1.opening_hours_pm_to }}
        </div>
    </div>

    <div class="grid-container-hours">        
        <div class="grid-item">
            <div class="weekdays-displayed">Mittwoch</div>
        </div>
        {{ hours_form.2.id }}
        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.2.opening_hours_am_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.2.opening_hours_am_to }}
        </div>

        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.2.opening_hours_pm_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.2.opening_hours_pm_to}}
        </div>
    </div>
    <div class="grid-container-hours">        
        <div class="grid-item">
            <div class="weekdays-displayed">Donnerstag</div>
        </div>
        {{ hours_form.3.id }}
        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.3.opening_hours_am_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.3.opening_hours_am_to }}
        </div>

        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.3.opening_hours_pm_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.3.opening_hours_pm_to }}
        </div>
    </div>
    <div class="grid-container-hours">        
        <div class="grid-item">
            <div class="weekdays-displayed">Freitag</div>
        </div>
        {{ hours_form.4.id }}
        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.4.opening_hours_am_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.4.opening_hours_am_to }}
        </div>

        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.4.opening_hours_pm_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.4.opening_hours_pm_to}}
        </div>
    </div>
    <div class="grid-container-hours">        
        <div class="grid-item">
            <div class="weekdays-displayed">Samstag</div>
        </div>
        {{ hours_form.5.id }}
        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.5.opening_hours_am_from }}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.5.opening_hours_am_to }}
        </div>

        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.5.opening_hours_pm_from }}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.5.opening_hours_pm_to}}
        </div>
    </div>
    <div class="grid-container-hours">        
        <div class="grid-item">
            <div class="weekdays-displayed">Sonntag</div>
        </div>
        {{ hours_form.6.id }}
        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.6.opening_hours_am_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.6.opening_hours_am_to}}
        </div>

        <div class="grid-item">
            <p>von:</p>
            {{ hours_form.6.opening_hours_pm_from}}
        </div>

        <div class="grid-item">
            <p>bis:</p>
            {{hours_form.6.opening_hours_pm_to}}
        </div>
    </div>
    
</div>

seiketsu/templates/dash/dashboard/profile/user_profile.html
{% extends 'dash/dashboard/dashboard.html' %}{% load static%} {% block dashboard_body_block%}

<div class="p-4 profil-username">
    <h1>{{usermodel_data.username}}</h1>
</div>

<div class="container p-5">

    <div class="row py-2">
        <div class="col-6 col-sm-3">
            <h4>Profildaten</h4>
        </div>
    </div>
    <div class="row py-2">
        <div class="col-8 info-text col-sm-6">
         Die hier angegebenen Profildaten werden in der Suche angezeigt und ermöglichen potentiellen Kunden
         Sie zu finden und mit Ihnen Kontakt aufzunehmen.
        </div>
        <div class="col-6 col-sm-3 w-50">

        </div>
    </div> 

    <div class="row py-2">
        <div class="col-3">
            <div class="col">
                <b>VAT</b>
            </div>
            <div class="row">
                <div class="col">
                     {{usermodel_type_data.uid}}
                </div>               
            </div>
        </div>
        <div class="col">
            <div class="col">
                <b>E-mail</b>
            </div>
            <div class="row">
                <div class="col">
                    {{usermodel_data.email}}
                </div>               
            </div>
        </div>
    </div>
   
    <div class="row py-2">
        <div class="col-3">
            <div class="col">
                <b>Adresse</b>
            </div>
            <div class="row">
                <div class="col">
                    {%if usermodel_adress_data.city %} 
                    {{usermodel_adress_data.street}},
                    {{usermodel_adress_data.city}},
                    {{usermodel_adress_data.zip_code}},
                    {{usermodel_adress_data.country}} {%else%}
                    <p>Jetzt angeben</p>
                    {%endif%}
                </div>
            </div>
        </div>
        
        <div class="col">
            <div class="col">
                <b>Unternehmensname</b>
            </div>
            <div class="row">
                <div class="col">
                {%if usermodel_data.first_name %} 
            {{usermodel_data.first_name}}
                {%else%}
                        <p>Jetzt angeben</p>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>

    <div class="row py-2">
        <div class="col-3">
            <div class="col">
                <b>Telefon</b>
            </div>
            <div class="row">
                <div class="col">
                    {%if usermodel_adress_data.phone %} 
                    {{usermodel_adress_data.phone}} {%else%}
                    <p>Jetzt angeben</p>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>

    <div class="py-2 row user_profile_btn_align d-flex justify-content-start manage-profile-password-change-grid">
        <div class="col  py-5 pr-0 d-flex justify-content-start">
            <a href="{% url 'Dash:modify_user_profile'%}">
                <button type="submit" class="btn profile-btn" >
                    <div class="grid-btn">
                    <div class="grid-btn-item-left1"><h5 >Profil bearbeiten</h5></div>
                    <div class="grid-btn-item-left2">Hier können Sie Ihre Profilangaben ändern oder nachtragen.</div>
                        <div class="grid-btn-arrow"><img class="btn-arrow-color" src="{%static '/images/icons/keyboard_double_arrow_right_black_24dp.svg' %}"></div>
            </div>
            </button></a>
        </div>

        <div class="col py-5 d-flex justify-content-start">
            <a href="{% url 'Dash:change_password'%}">
                <button type="submit" class="btn profile-btn" >
                    <div class="grid-btn">
                    <div class="grid-btn-item-left1"><h5 >Passwort ändern</h5></div>
                    <div class="grid-btn-item-left2">Revitalyze-Passwort anpassen (in regelmässigen Abständen empfholen)</div>
                        <div class="grid-btn-arrow"><img class="btn-arrow-color" src="{%static '/images/icons/keyboard_double_arrow_right_black_24dp.svg' %}"></div>
            </div>
            </button></a>
        </div>
    </div>

    <div class="row py-2">
        <div class="col-6 col-sm-3">
            <h4>Standorte</h4>
        </div>
    </div>
    <div class="row py-4">
        <div class="col-8 info-text col-sm-6">
            Ein Standort kann eine Deponie, eine Recyclinganlage oder eine sonstige Annahmestelle für Materialien sein.
        </div>
        <div class="col-6 col-sm-3 w-50">

        </div>
    </div> 

    <div class="row py-2 user_profile_btn_align">

        <div class="col">
            {%if usermodel_gln_data %}
                        {% for gln_data in usermodel_gln_data%} 
                            <div class="row">
                                <div class="col">
                                    <a href="{% url 'Dash:add_gln'%}?gln-id={{gln_data.id}}">
                                        <button type="submit" class="btn profile-btn py-2 gln-location-profile-btn" >
                                            <div class="grid-btn-gln-location-profile">
                                                <div class="grid-btn-gln-location-profile-item-left1 ">
                                                <div class="col"> <img class="btn-gln-place-color" src="{%static '/images/icons/place_black_24dp.svg' %}"></div>
                                                    <div class="col"> <h5 >{{gln_data.adress}}</h5> </div>
                                                </div>
                                                {% if gln_data.gln %}
                                                    <div class="grid-btn-gln-location-profile-left2"> 
                                                        Gln: {{gln_data.gln}}
                                                    </div>
                                                {% endif %}
                                            <div class="grid-btn-gln-location-profile-arrow">
                                                <img class="btn-arrow-color" src="{%static '/images/icons/arrow_right_alt_black_24dp.svg' %}">
                                            </div>
                                        </div>
                                        </button>
                                    
                                    </a>
                                </div>
                                <div class="col d-flex align-items-center">
                                <form method="post" enctype="multipart/form-data">
                                    {%csrf_token%}
                                    <input type="hidden" name="delete_gln" value="{{gln_data.id}}" />
                                    <button type="submit" class="btn btn-delete py-2" >
                                        <i class="bi bi-x-square-fill" style="color:red;"></i>
                                    </button>
                                </form>
                            </div>
                            </div>
                        {% endfor %}
                    </div>
                </div> 
                <div class="row">
                        <div class="col jumbotron d-flex py-3 justify-content-start">
                            <div style="height: 500px; width: 800px;" id="map">map</div>
                                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDU9z_Yz39-G4AjERSbxZOlwdeM92d3Kcg&callback=initMap" async></script>
                        
            {%else%}
                <p class="p-5">Es sind noch keine GLN-Daten vorhanden</p>
            {%endif%}
            </div>
        </div>
    

    <div class="row py-2 d-flex justify-content-start user_profile_btn_align">
        <div class="col w-100 d-flex py-3 justify-content-start">
            <a href="{% url 'Dash:add_gln'%}"><button type="submit" class="btn profile-btn" >
                <div class="grid-btn">
                <div class="grid-btn-item-left1"><h5 >Neuen Standort hinzufügen</h5></div>
                <div class="grid-btn-item-left2"> Lege Preislisten an, setze Öffnungszeiten fest und füge Adresse und Sonderbestimmungen hinzu.</div>
                    <div class="grid-btn-arrow"><img class="btn-arrow-color" src="{%static '/images/icons/keyboard_double_arrow_right_black_24dp.svg' %}"></div>
        </div>
        </button></a>
        
        </div>
    </div>
    <script type="text/javascript">
        let location_points = [];
        let gln_data_unsplitted;
        let splitted_points;
        let nameForMarker;
        {% for gln_data in usermodel_gln_data%} 
            gln_data_unsplitted = "{{gln_data.location}}";
            splitted_points = gln_data_unsplitted.split('(')[1].split(')')[0];
            nameForMarker = '{{gln_data.id}}';
            location_points.push(splitted_points); 
        {% endfor %}

    </script>

</div>

{% endblock %}